services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: book_service
    ports:
      - "5432:5432"
    volumes:
      - bookpoisk_pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "4000:4000"

volumes:
  bookpoisk_pgdata:
